// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Prisma 7 CLI loads env vars HERE (not from schema.prisma).
//
// Next.js keeps real secrets in .env.local (gitignored). The default
// `import "dotenv/config"` only loads .env — which holds the prisma init
// stub (localhost placeholder). So we explicitly load .env.local first,
// then fall back to .env. .env.local wins because it's loaded first and
// dotenv does not override existing process.env keys by default.
config({ path: ".env.local" });
config({ path: ".env" });

// In Prisma 7, connection URLs live HERE (not in schema.prisma).
//
// `datasource.url` is used by the Prisma CLI for migrate / introspect / push.
// It MUST be the DIRECT (non-pooled) Neon connection so migrations can run
// DDL and prepared statements — PgBouncer's transaction mode breaks those.
// We prefer DIRECT_URL when set, and fall back to DATABASE_URL.
const migrationUrl =
  process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationUrl,
  },
});
